### ISSUE TITLE
Generation of targets

### ISSUE THREAD

**Issue by jzwart** [eco4cast/usgsrc4cast-ci#3]
This [workflow is running](https://github.com/eco4cast/usgsrc4cast-ci/actions/runs/7283855054), but still need to push the targets somewhere. 

@rqthomas and @cboettig , where should I push the targets for a new forecast challenge? Should I use [this bucket](https://github.com/eco4cast/neon4cast-ci/blob/17d53d3ebd6b39bfa6a6ee8a20eba116845333fd/challenge_configuration.yaml#L13) and partition using `project_id` and `duration`, [e.g.,](https://github.com/eco4cast/neon4cast-ci/blob/17d53d3ebd6b39bfa6a6ee8a20eba116845333fd/targets/aquatics_targets.R#L762) ? The aquatics targets for neon4cast also pushes to [a different bucket / endpoint](https://github.com/eco4cast/neon4cast-ci/blob/17d53d3ebd6b39bfa6a6ee8a20eba116845333fd/targets/aquatics_targets.R#L749) - is this because this is where those data were pushed historically?

**Comment by rqthomas** [comment]
We are pushing to two different buckets for the neon4cast so that we don't break existing workflows.  Use the one in the neon4cast config files (which should already be in your configuration file)

**Comment by jzwart** [comment]
closed with #15
