### ISSUE TITLE
Download of weather drivers for forecasts

### ISSUE THREAD

**Issue by jzwart** [eco4cast/usgsrc4cast-ci#5]

**Comment by jzwart** [comment]
Added to repo with #17  and in progress with https://github.com/eco4cast/usgsrc4cast-ci/actions/runs/7644576184

**Comment by jzwart** [comment]
@rqthomas  and @cboettig , I have a job running on `efi-runner-cirrus` to back fill all GEFS driver data for USGS sites from 2020 to present day https://github.com/eco4cast/usgsrc4cast-ci/actions/runs/7644576184 . I think you said it'd take ~6 days. Will this block other jobs from getting started on `efi-runner-cirrus` ?  I could always stop / restart this job periodically to let other jobs run if necessary.

**Comment by cboettig** [comment]
@jzwart cool, thanks for the heads up.  let's have it run and see how it goes?

We have two runners registered to the org (https://github.com/organizations/eco4cast/settings/actions/runners), so the second runner should still be able to pick up jobs.  @rqthomas let me know if there's issues? 


Those two runners are actually pointing at the same workstation in my lab ('cirrus') but in separate virtual containers. 

I think a cool thing about this whole setup is that it's relatively easy to add and remove self-hosted runners into the pool, and they can also be tagged / selected based on the resources they provide.  This means I think it would be easy to pool resources across different groups, which I think could be very powerful...

**Comment by jzwart** [comment]
awesome, yeah that's a great setup. So we could specify something like `[self-hosted, gpu]` if there's a runner with GPU capability and tag. 

I assume only `owners` of the eco4cast organization can add new runners as I can't see those settings you linked to. I could add a new self-hosted runner to this usgsrc4cast repo that I created though (although would only be available for this repo).

**Comment by cboettig** [comment]
yup, precisely.  

at some point EFI should probably have some governance policy on how to manage who is an owner and related permissions stuff.

**Comment by rqthomas** [comment]
I just pinged Jody to add it to the EFI steering committee discussion list.
